const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const CONFIG={whatsapp:"+201000000000",price:null}; // غيّر الرقم والسعر من لوحة الإدارة لاحقًا.
const T=[
{id:"noir",name:"Noir Luxury",cat:"luxury",desc:"أسود وذهبي — فخم وسينمائي"},
{id:"rose",name:"Rose Romance",cat:"romantic",desc:"وردي ناعم — رومانسي"},
{id:"ivory",name:"Ivory Classic",cat:"classic",desc:"عاجي وشامبين — كلاسيك"},
{id:"emerald",name:"Emerald Night",cat:"luxury",desc:"زمردي — ملكي"},
{id:"modern",name:"Modern Editorial",cat:"modern",desc:"مودرن — صور ومربعات"},
{id:"arabic",name:"Arabic Heritage",cat:"classic",desc:"عربي — زخارف دافئة"}];
let chosen=null,step=1,cover="",gallery=[],music="",data=null;
const P={market:$("#market"),builder:$("#builder"),payment:$("#payment"),success:$("#success"),invite:$("#invite")};
function hide(){Object.values(P).forEach(x=>x.classList.add("hidden"))}function toast(x){let t=$("#toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2000)}
function wa(text){return"https://wa.me/"+CONFIG.whatsapp.replace(/\D/g,"")+"?text="+encodeURIComponent(text)}
$("#wa").href=wa("السلام عليكم، عايز أعمل دعوة إلكترونية.");
function render(filter="all"){$("#templates").innerHTML=T.filter(x=>filter==="all"||x.cat===filter).map(x=>`<article class="template ${x.id}"><div class="thumb"><div class="fake"><small>دعوة زفاف</small><h2>Mohamed ♥ Fatima</h2><hr><p>الخميس · 24 سبتمبر 2026</p></div></div><div class="info"><b>${x.name}</b><small>${x.desc}</small><div class="two"><button data-prev="${x.id}">معاينة كاملة</button><button class="apply" data-app="${x.id}">تطبيق</button></div></div></article>`).join("");$$("[data-prev]").forEach(b=>b.onclick=()=>preview(b.dataset.prev));$$("[data-app]").forEach(b=>apply(b.dataset.app))}
$$(".filters button").forEach(b=>b.onclick=()=>{$$(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.f)});render();
const modal=$("#modal");function getT(id){return T.find(x=>x.id===id)}function preview(id){chosen=getT(id);$("#modalTitle").textContent=chosen.name;$("#preview").innerHTML=`<div class="demo"><div class="demoCover"><div><small>دعوة زفاف</small><h2>Mohamed ♥ Fatima</h2><hr><p>الخميس · 24 سبتمبر 2026</p></div></div><div class="demoBody"><small>تفاصيل المناسبة</small><div class="demoBox">قاعة الرومانسية<br>القاهرة · 08:00 مساءً<br><button class="btn2">الموقع على الخريطة</button></div><div class="demoBox">باقي على الفرح<br><h2>31 · 19 · 26 · 09</h2></div><div class="demoGallery"><i></i><i></i><i></i><i></i></div><div class="demoBox">هتشرفونا؟<br><button class="btn">تأكيد الحضور</button></div></div><div class="demoNav">💬<br>التهاني &nbsp; ♡<br>الحضور &nbsp; ▦<br>الصور &nbsp; ⌖<br>الموقع &nbsp; ◷<br>العداد</div></div>`;modal.classList.remove("hidden")}
$("#close").onclick=()=>modal.classList.add("hidden");$("#modal").querySelector(".shade").onclick=()=>modal.classList.add("hidden");$("#modalApply").onclick=()=>{modal.classList.add("hidden");apply(chosen.id)};$("#modalApply2").onclick=()=>{modal.classList.add("hidden");apply(chosen.id)};
function apply(id){chosen=getT(id);$("#chosenName").textContent=chosen.name;hide();P.builder.classList.remove("hidden");go(1)}
$("#change").onclick=()=>{hide();P.market.classList.remove("hidden")};
function go(n){step=n;$$(".step").forEach(x=>x.classList.toggle("active",+x.dataset.s===n));$("#bar").style.width=n/6*100+"%";$("#back").classList.toggle("hidden",n===1);$("#next").classList.toggle("hidden",n===6);$("#review").classList.toggle("hidden",n!==6);if(n===6)summary();scrollTo(0,0)}
function valid(){for(const f of $(`.step[data-s="${step}"]`).querySelectorAll("[required]"))if(!f.value.trim()){f.focus();toast("كمّل البيانات المطلوبة");return false}return true}
$("#next").onclick=()=>{if(valid())go(Math.min(6,step+1))};$("#back").onclick=()=>go(Math.max(1,step-1));
function read(f){return new Promise((ok,no)=>{let r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)})}
$("#cover").onchange=async e=>{if(e.target.files[0]){cover=await read(e.target.files[0]);$("#coverPreview").src=cover;$("#coverPreview").style.display="block"}};
$("#gallery").onchange=async e=>{gallery=await Promise.all([...e.target.files].slice(0,20).map(read));$("#galleryPreview").innerHTML=gallery.map(x=>`<img src="${x}">`).join("")};
$("#music").onchange=async e=>{if(e.target.files[0]){music=await read(e.target.files[0]);toast("تم اختيار الأغنية")}};
function collect(){return{template:chosen.id,templateName:chosen.name,groom:$("#groom").value.trim(),bride:$("#bride").value.trim(),headline:$("#headline").value.trim()||"يسعدنا أن نشارككم أجمل أيامنا",welcome:$("#welcome").value.trim()||"وجودكم هو أجمل هدية لنا",date:$("#date").value,time:$("#time").value,event:$("#event").value,city:$("#city").value,venue:$("#venue").value,maps:$("#maps").value,cover,gallery,music,rsvp:$("#rsvp").checked,showMaps:$("#showMaps").checked,calendar:$("#calendar").checked,messages:$("#messages").checked,slug:$("#slug").value.trim().toLowerCase().replace(/[^a-z0-9-]+/g,"-"),customer:$("#customer").value,phone:$("#phone").value,payment:"pending"}}
function summary(){data=collect();$("#summary").innerHTML=Object.entries({التصميم:data.templateName,الأسماء:data.groom+" ♥ "+data.bride,الموعد:data.date+" "+data.time,المكان:data.venue,الرابط:data.slug,واتساب:data.phone}).map(([a,b])=>`<div><small>${a}</small><b>${b||"—"}</b></div>`).join("")}
$("#sendWA").onclick=()=>{data=collect();if(!data.customer||!data.phone){toast("اكتب اسمك ورقم واتساب");return}location.href=wa(`طلب دعوة — ${data.templateName}%0A${data.groom} ♥ ${data.bride}%0A${data.date} ${data.time}%0A${data.venue}%0Aالرابط: ${data.slug}%0Aالعميل: ${data.customer}%0Aواتساب: ${data.phone}`)};
$("#form").onsubmit=e=>{e.preventDefault();if(!valid())return;data=collect();if(!data.slug){toast("اكتب اسم الرابط");return}hide();P.payment.classList.remove("hidden");$("#paySummary").innerHTML=`<div class="summary"><div><small>التصميم</small><b>${data.templateName}</b></div><div><small>الأسماء</small><b>${data.groom} ♥ ${data.bride}</b></div><div><small>الرابط</small><b>${data.slug}</b></div></div>`};
$("#edit").onclick=()=>{hide();P.builder.classList.remove("hidden");go(6)};
$("#manualPay").onclick=()=>location.href=wa(`أنا جاهز للدفع لتفعيل الدعوة ${data.slug}. الاسم: ${data.customer} - واتساب: ${data.phone}`);
$("#onlinePay").onclick=()=>{if(window.PAYMENT_CHECKOUT_URL)location.href=window.PAYMENT_CHECKOUT_URL;else toast("زر الدفع جاهز للربط بـ Paymob من الـBackend — لا نعتبر الدفع ناجحًا من المتصفح.")};
function activate(){data.payment="paid";localStorage.setItem("invite_"+data.slug,JSON.stringify(data));hide();P.success.classList.remove("hidden");let u=location.origin+location.pathname+"?invite="+encodeURIComponent(data.slug);$("#link").textContent=u;$("#open").onclick=()=>location.href=u;$("#copy").onclick=()=>navigator.clipboard.writeText(u).then(()=>toast("تم نسخ الرابط"))}
function renderInvite(d){hide();P.invite.classList.remove("hidden");$("#names").innerHTML=`${esc(d.groom)} ♥ ${esc(d.bride)}`;$("#headView").textContent=d.headline;$("#welcomeView").textContent=d.welcome;$("#dateView").textContent=d.date;$("#eventView").textContent=d.event;$("#venueView").textContent=d.venue;$("#locView").textContent=d.city;$("#timeView").textContent=d.time?`الساعة ${d.time}`:"";if(d.cover)$("#coverView").style.backgroundImage=`linear-gradient(#0002,#000c),url("${d.cover}")`;$("#mapView").classList.toggle("hidden",!(d.maps&&d.showMaps));if(d.maps)$("#mapView").href=d.maps;$("#cal").classList.toggle("hidden",!d.calendar);$("#rsvpSec").classList.toggle("hidden",!d.rsvp);$("#msgSec").classList.toggle("hidden",!d.messages);$("#photos").innerHTML=(d.gallery||[]).map(x=>`<img src="${x}">`).join("");if(d.music){$("#audio").src=d.music;$("#audio").play().catch(()=>{})}let target=new Date(d.date+"T"+(d.time||"00:00"));setInterval(()=>{let q=Math.max(0,Math.floor((target-new Date())/1000));$("#d").textContent=String(Math.floor(q/86400)).padStart(2,"0");$("#h").textContent=String(q%86400/3600|0).padStart(2,"0");$("#m").textContent=String(q%3600/60|0).padStart(2,"0");$("#s").textContent=String(q%60).padStart(2,"0")},1000)}
function esc(s=""){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
$("#enter").onclick=()=>$("#welcomeView").scrollIntoView({behavior:"smooth"});$("#minus").onclick=()=>$("#count").textContent=Math.max(1,+$("#count").textContent-1);$("#plus").onclick=()=>$("#count").textContent=Math.min(20,+$("#count").textContent+1);$("#rsvpBtn").onclick=()=>toast("تم تسجيل حضورك ❤️");$("#msgBtn").onclick=()=>toast("وصلت التهنئة ❤️");
const q=new URLSearchParams(location.search).get("invite");if(q){let d=JSON.parse(localStorage.getItem("invite_"+q)||"null");if(d&&d.payment==="paid")renderInvite(d);else go(1)}else go(1);
